version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: attendance_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: attendance_db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: